##################################
### JobsReborn-PatchPlaceBreak ###
##################################

# Define where to store and retrieve patch tags.
dataSource:
  # The database manager to use.
  # Available values:
  # - SQLITE: use a local file as database (easy setup)
  # - MYSQL: use a MySQL database server (better performances)
  type: 'SQLITE'

  # The table name where data will be stored.
  table: 'patch_place_break_tag'

  # If type is set to 'SQLITE', dbmsServer part can be ignored.
  dbmsServer:
    host:
      hostname: 'localhost'
      port: 3306
      isSslEnabled: true
    credentials:
      username: 'username'
      password: 'password'
    database: 'patch_place_break'
