##################################
### JobsReborn-PatchPlaceBreak ###
##################################

# Define where to store and retrieve data.
dataSource:
  # The type of datasource to use.
  # Available types:
  # - SQLITE: use a local file as database (easy setup)
  # - MYSQL: use a MySQL database server (better performances)
  type: 'SQLITE'

  # The table name where data will be stored.
  table: 'patch_place_break_tag'

  # The DBMS server properties to establish connections.
  # If type is set to 'SQLITE', this part can be safely ignored.
  dbmsServer:
    host:
      hostname: 'localhost'
      port: 3306
      isSslEnabled: true
    credentials:
      username: 'username'
      password: 'password'
    database: 'database'

  # Connection pool properties.
  # This is reserved for advanced usage only.
  # Change these settings only if you know what you are doing.
  connectionPool:
    # The connection timeout in milliseconds.
    # Corresponds to the maximum time the connection pool will wait to acquire a new connection
    # from the DBMS server.
    # Not applicable for SQLite.
    # Accepted range values: [1-600000]
    connectionTimeout: 30000

    # The number of DBMS connections in the pool.
    # Could be best determined by the executing environment.
    # Accepted range values: [1-100]
    poolSize: 10

