tag_prefix = "v"

pre_bump_hooks = [
  "git switch --create release/{{version_tag}}",
]
post_bump_hooks = [
  "git push --set-upstream origin release/{{version_tag}}"
]

[commit_types]
feat = { changelog_title = "🌟 Features" }
fix = { changelog_title = "🐛 Bug Fixes" }
perf = { changelog_title = "⚡ Performances" }
revert = { changelog_title = "↩️ Revert" }
docs = { changelog_title = "📖 Documentation" }
test = { changelog_title = "✅ Tests" }
build = { changelog_title = "🏗️ Build System" }
ci = { changelog_title = "📦 Continuous Integration" }
refactor = { changelog_title = "🛠️ Refactoring" }
chore = { changelog_title = "🧹 Miscellaneous Chores" }
style = { changelog_title = "🖌️ Style" }

[changelog]
path = ".github/CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "Djaytan"
repository = "mc-jobs-reborn-patch-place-break"
authors = [
  { signature = "Djaytan", username = "Djaytan" }
]
