tag_prefix = "v"
branch_whitelist = [
  "main"
]

# Perform the following steps:
# 1. Update pom.xml files with the new version being prepared
# 2. Generate the Spigot plugin & associated sources and Javadoc JAR files
# 3. Reset the Git working tree. Generated JAR files at step 2 will be kept
# 4. Let Cocogitto generate the CHANGELOG file, commit it, and create a tag above it
# 5. Push the commit on remote
# 6. Push the tag on remote
pre_bump_hooks = [
  "mvn versions:set -DnewVersion='{{version}}' --batch-mode --errors",
  "mvn clean package --activate-profiles fast --batch-mode --errors --strict-checksums --update-snapshots --fail-fast",
  "git restore ."
]
post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}"
]

[commit_types]
feat = { changelog_title = "🌟 Features" }
fix = { changelog_title = "🐛 Bug Fixes" }
perf = { changelog_title = "⚡ Performances" }
revert = { changelog_title = "↩️ Revert" }
docs = { changelog_title = "📖 Documentation" }
test = { changelog_title = "✅ Tests" }
build = { changelog_title = "🏗️ Build System" }
ci = { changelog_title = "📦 Continuous Integration" }
refactor = { changelog_title = "🛠️ Refactoring" }
chore = { changelog_title = "🧹 Miscellaneous Chores" }
style = { changelog_title = "🖌️ Style" }

[changelog]
path = ".github/CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "Djaytan"
repository = "mc-jobs-reborn-patch-place-break"
authors = [
  { signature = "Djaytan", username = "Djaytan" }
]
