tag_prefix = "v"
branch_whitelist = [
  "main"
]

pre_bump_hooks = [
  "mvn versions:set -DnewVersion='{{version}}' -DgenerateBackupPoms=false --errors",
  "mvn clean package -DskipTests --activate-profiles fast --errors --strict-checksums --update-snapshots --fail-fast"
]
post_bump_hooks = [
  "mvn versions:set -DnewVersion='0.0.1-DEV-SNAPSHOT' -DgenerateBackupPoms=false --errors",
  "git commit --all --message='chore: prepare for next development iteration [ci skip]'",
  "git push",
  "git push origin {{version_tag}}"
]

[commit_types]
feat = { changelog_title = "🌟 Features" }
fix = { changelog_title = "🐛 Bug Fixes" }
perf = { changelog_title = "⚡ Performances" }
revert = { changelog_title = "↩️ Revert" }
docs = { changelog_title = "📖 Documentation" }
test = { changelog_title = "✅ Tests" }
build = { changelog_title = "🏗️ Build System" }
ci = { changelog_title = "📦 Continuous Integration" }
refactor = { changelog_title = "🛠️ Refactoring" }
chore = { changelog_title = "🧹 Miscellaneous Chores" }
style = { changelog_title = "🖌️ Style" }

[changelog]
path = ".github/CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "Djaytan"
repository = "mc-jobs-reborn-patch-place-break"
authors = [
  { signature = "Djaytan", username = "Djaytan" }
]
