version: 2.1

executors:
  build-executor:
    docker:
      - image: 'cimg/openjdk:8.0'
    environment:
      MAVEN_CLI_OPTS: '-Pcontinuous-integration -e -C --fail-at-end --no-transfer-progress'
      POST_BUILD_MAVEN_CLI_OPS: '-Dmaven.compiler.useIncrementalCompilation=false'
  sonar-executor:
    docker:
      - image: 'cimg/openjdk:11.0'
    environment:
      MAVEN_CLI_OPTS: '-Pcontinuous-integration -e -C --fail-at-end --no-transfer-progress'

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - restore_cache:
          name: 'cache/restoreDependencies'
          keys:
            - 'v2-maven-local-repository-cache-{{ checksum "pom.xml" }}'
      - run:
          name: 'mvn/validate'
          command: mvn $MAVEN_CLI_OPTS validate
      - run:
          name: 'mvn/build'
          command: mvn $MAVEN_CLI_OPTS test-compile
      - save_cache:
          name: 'cache/saveDependencies'
          key: 'v2-maven-local-repository-cache-{{ checksum "pom.xml" }}'
          paths:
            - '~/.m2'
      - persist_to_workspace:
          root: '~/project'
          paths:
            - '*'
  test:
    executor: build-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - run:
          name: 'mvn/unitTests'
          command: mvn $MAVEN_CLI_OPTS $POST_BUILD_MAVEN_CLI_OPS test
      - run:
          name: 'mvn/integrationTests'
          command: mvn $MAVEN_CLI_OPTS $POST_BUILD_MAVEN_CLI_OPS verify -DskipUnitTests
      - run:
          name: 'mvn/finalize'
          command: mvn $MAVEN_CLI_OPTS $POST_BUILD_MAVEN_CLI_OPS install -Dmaven.test.skip=true
      - run:
          name: 'publish/testResults'
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      - store_test_results:
          path: '~/test-results/junit/'
      - persist_to_workspace:
          root: '~/project'
          paths:
            - '*'
  sonar:
    executor: sonar-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - run:
          name: 'mvn/sonar'
          command: mvn sonar:sonar -Dsonar.projectKey=Djaytan_mc-jobs-reborn-patch-place-break

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar:
          requires:
            - test
          context: SonarCloud
