version: 2.1

jobs:
  maven-job:
    docker:
      - image: 'cimg/openjdk:11.0'
    environment:
      MAVEN_CLI_OPTS: '-Pcontinuous-integration -e -C --fail-at-end --no-transfer-progress'
    steps:
      - checkout
      - restore_cache:
          name: 'cache/restore'
          keys:
            - 'v2-maven-local-repository-cache-{{ checksum "pom.xml" }}'
      - run:
          name: 'mvn/format'
          command: mvn $MAVEN_CLI_OPTS validate
      - run:
          name: 'mvn/build'
          command: mvn $MAVEN_CLI_OPTS compile
      - run:
          name: 'mvn/unitTests'
          command: mvn $MAVEN_CLI_OPTS test
      - run:
          name: 'mvn/integrationTests'
          command: mvn $MAVEN_CLI_OPTS verify -DskipUnitTests
      - run:
          name: 'sonar/analysis'
          command: mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dmaven.test.skip=true
      - save_cache:
          name: 'cache/save'
          key: 'v2-maven-local-repository-cache-{{ checksum "pom.xml" }}'
          paths:
            - '~/.m2'

workflows:
  main:
    jobs:
      - maven-job:
          context: SonarCloud
