version: 2.1

jobs:
  maven-job:
    docker:
      - image: 'maven:3.8.6-eclipse-temurin-8'
    environment:
      MAVEN_CLI_OPTS: '-Pformat-checker -e -C --fail-at-end --no-transfer-progress'
    steps:
      - checkout
      - restore_cache:
          name: 'cache/restore'
          keys:
            - 'v1-maven-local-repository-cache-{{ checksum "pom.xml" }}'
      - run:
          name: 'mvn/format'
          command: mvn $MAVEN_CLI_OPTS validate
      - run:
          name: 'mvn/build'
          command: mvn $MAVEN_CLI_OPTS compile
      - run:
          name: 'mvn/test'
          command: mvn $MAVEN_CLI_OPTS test
      - run:
          name: 'mvn/package'
          command: mvn $MAVEN_CLI_OPTS package -DskipTests
      - save_cache:
          name: 'cache/save'
          key: 'v1-maven-local-repository-cache-{{ checksum "pom.xml" }}'
          paths:
            - $MAVEN_CONFIG

workflows:
  main:
    jobs:
      - maven-job
