name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '28 14 * * *' # At 14:28 every day

permissions: {}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 300

    permissions:
      contents: read

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            objects.githubusercontent.com:443
            repo.maven.apache.org:443
            jitpack.io:443
            repo.papermc.io:443
            auth.docker.io:443
            registry-1.docker.io:443
            production.cloudflare.docker.com:443
            sonarcloud.io:443
            scanner.sonarcloud.io:443
            ea6ne4j2sb.execute-api.eu-central-1.amazonaws.com:443
            sc-cleancode-sensorcache-eu-central-1-prod.s3.amazonaws.com:443

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          # Required by SonarCloud & Cocogitto
          fetch-depth: 0
          # Pick the PR HEAD instead of the merge commit (required by Cocogitto)
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@ac6260150ee57e3164cd95b47fc84cdee9e3444c # v3.5
        with:
          check-latest-tag-only: true

      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Testcontainers - Enable reusable containers
        run: echo 'testcontainers.reuse.enable=true' >> ~/.testcontainers.properties

      - name: Cache SonarCloud packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.sonar/cache
          key: sonar
          restore-keys: sonar

      - name: Maven build & SonarCloud quality scan
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: |
          SONAR_ORGANIZATION="$(echo '${{ github.repository_owner }}' | awk '{print tolower($0)}')"
          SONAR_PROJECT_KEY="$(echo '${{ github.repository }}' | sed 's/\//_/')"

          mvn verify sonar:sonar --activate-profiles ci \
            --batch-mode --errors --strict-checksums --update-snapshots \
            -Dsonar.host.url="${SONAR_HOST_URL}" \
            -Dsonar.organization="${SONAR_ORGANIZATION}" \
            -Dsonar.projectKey="${SONAR_PROJECT_KEY}"

  security-scan:
    name: Security scan
    runs-on: ubuntu-latest
    timeout-minutes: 300

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            uploads.github.com:443
            repo.maven.apache.org:443
            jitpack.io:443
            repo.papermc.io:443

      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@012739e5082ff0c22ca6d6ab32e07c36df03c4a4 # v3.22.12
        with:
          languages: java

      - name: Build
        run: |
          mvn package --activate-profiles fast \
            --batch-mode --errors --strict-checksums --update-snapshots --fail-fast

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@012739e5082ff0c22ca6d6ab32e07c36df03c4a4 # v3.22.12
        with:
          category: /language:java
