name: CI/CD

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  MAVEN_MAIN_ARGS: -Pcontinuous-integration -U -B -e -C --fail-at-end
  MAVEN_SKIP_ARGS: -DskipTests=true -DskipITs=true -Dfmt.skip=true -Dsort.skip=true -Denforcer.skip=true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build & Test
        run: mvn ${{ env.MAVEN_MAIN_ARGS }} verify
      - name: SonarCloud Quality Scan
        run: mvn sonar:sonar -Dsonar.projectKey=Djaytan_mc-jobs-reborn-patch-place-break
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Perform part not required with Jitpack
  cd-prepare:
    name: CD - Prepare
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: qcastel/github-actions-maven-release@v1.12.39
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          maven-args: ${{ env.MAVEN_MAIN_ARGS }} ${{ env.MAVEN_SKIP_ARGS }} -Dmaven.javadoc.skip=true
          release-branch-name: 'main'
          skip-perform: true
          git-release-bot-email: '41898282+github-actions[bot]@users.noreply.github.com'
