name: Maven - CI

# All release branches are supposed to follow SemVer convention while being restricted
# to only the major.minor part.
# Filtering performed based on recommended RegEx from semver.org:
# https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
# The pattern has been adapted since workflow syntax doesn't support RegEx.
on:
  push:
    # Re-execute the CI only for status and ensure the default branch remains stable in any circumstances
    branches:
      - 'main'
    paths:
      - '**/pom.xml'
      - '.github/workflows/*'
      - 'src/**'
  pull_request:
    branches:
      - 'main'
      - 'release/v0.0'
      - 'release/v0.[1-9][0-9]*'
      - 'release/v[1-9][0-9]*.0'
      - 'release/v[1-9][0-9]*.[1-9][0-9]*'
    paths:
      - '**/pom.xml'
      - '.github/workflows/*'
      - 'src/**'

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          # SonarQube - Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: 17
          distribution: temurin

      - name: Testcontainers - Enable reusable containers
        run: echo 'testcontainers.reuse.enable=true' >> ~/.testcontainers.properties

      - name: Cache local Maven repository
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.m2/repository
          key: m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2

      - name: Cache SonarCloud packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.sonar/cache
          key: sonar
          restore-keys: sonar

      - name: SonarCloud Quality Scan
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar -Pci -B -C -U -ntp -fae -e \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=djaytan \
            -Dsonar.projectKey=Djaytan_mc-jobs-reborn-patch-place-break
