name: Release - Perform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - .github/CHANGELOG.md

permissions:
  contents: read

jobs:
  release-perform:
    name: Release - Perform
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # PAT required for bypassing tag protection
          token: ${{ secrets.PUSH_TOKEN }}
          # Required for tag existence check
          fetch-depth: 0

      - name: Verify compliant commit message and extract release version
        id: extract
        run: |
          COMMIT_MESSAGE="$(git show --pretty=format:"%s" -s "${{ github.sha }}")"

          if [[ ! "${COMMIT_MESSAGE}" =~ ^chore\(version\):\ (v([0-9]+\.[0-9]+\.[0-9]+))$ ]]; then
            echo "Non-expected commit message: '${COMMIT_MESSAGE}'"
            echo 'Aborting...'
            exit 1
          fi

          echo "The following commit message is compliant: '${COMMIT_MESSAGE}'"
          echo 'Continuing...'

          RELEASE_VERSION="${BASH_REMATCH[1]}"
          UNPREFIXED_RELEASE_VERSION="${BASH_REMATCH[2]}"

          echo "Extracted release version: ${RELEASE_VERSION} (without prefix: ${UNPREFIXED_RELEASE_VERSION})"

          echo "version=${RELEASE_VERSION}" >> "${GITHUB_OUTPUT}"
          echo "unprefixed-version=${UNPREFIXED_RELEASE_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Create and push tag
        run: |
          RELEASE_VERSION='${{ steps.extract.outputs.version }}'

          if [[ -n "$(git tag -l "${RELEASE_VERSION}")" ]]; then
            echo "The tag '${RELEASE_VERSION}' already exists"
            echo 'Aborting...'
            exit 1
          fi

          echo "The tag '${RELEASE_VERSION}' does not exist yet"
          echo 'Continuing...'

          git tag "${RELEASE_VERSION}"
          git push origin refs/tags/"${RELEASE_VERSION}"

      - name: Publish GitHub release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: src/spigot-plugin/target/JobsReborn-PatchPlaceBreak-${{ steps.extract.outputs.unprefixed-version }}.jar
          fail_on_unmatched_files: true
          body_path: .github/CHANGELOG.md
          tag_name: ${{ steps.extract.outputs.version }}
